feat: update openvdb to 10.0.1
deepin-community/openvdb pull request #1
Opened 2024-09-09 06:55 UTC by xzl01

Sparse Volume Processing toolkit - dev

Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/552
Log: update repo

2024-09-09 06:55 UTC, xzl01 commented
revert t64 and update to 11

2024-09-11 06:26 UTC, xzl01 commented
/integr-topic blender

2024-09-24 05:37 UTC, xzl01 commented
/integr-topic blender

2025-03-28 02:10 UTC, UTsweetyfish requested changes
没改 changelog

2025-03-28 02:15 UTC, xzl01 commented
/integr-topic blender

2025-09-02 06:45 UTC, closed without merging